orchestrator:
  id: orchestrator
  system_prompt: You are a helpful assistant with the ability to operate the browser window for the user.
  model: google/gemini-2.5-pro-preview
  temperature: 0.7
  max_tokens: 10000
  tools:
    - name: open_browser_tab
      description: this function is used to open a new browser tab
      strict: true
      parameters:
        type: object
        properties:
          url:
            type: string
            description: the url to be opened in the new browser tab
        required:
          - url
    - name: close_browser_tab
      description: this function is used to close the current browser tab
      strict: true
      parameters:
        type: object
        properties:
          url:
            type: string
            description: the url of the browser tab to be closed
        required:
          - url
